# Generated by Django 3.1.5 on 2022-02-26 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20220225_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='name',
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='contents',
        ),
        migrations.RemoveField(
            model_name='book',
            name='name',
        ),
        migrations.AddField(
            model_name='genre',
            name='name_japanese',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Name (Japanese)'),
        ),
        migrations.AddField(
            model_name='genre',
            name='name_romaji',
            field=models.CharField(blank=True, default=None, max_length=70, null=True, verbose_name='Name (Romaji)'),
        ),
        migrations.AddField(
            model_name='book',
            name='JLPT_level',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='contents_japanese',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Contents (Japanese)'),
        ),
        migrations.AddField(
            model_name='book',
            name='contents_romaji',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Contents (Romaji)'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_japanese',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Name (Japanese)'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_romaji',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Name (Romaji)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.genre'),
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('story', models.CharField(blank=True, choices=[('POEM', 'Poem'), ('SHORT', 'Short Story'), ('OTHER', 'Other')], default=None, max_length=25, null=True)),
                ('genre', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='books.genre')),
                ('book', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='books.book')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('genres', models.ManyToManyField(related_name='authors', to='books.Genre')),
                ('books', models.ManyToManyField(related_name='authors', to='books.Book')),
            ],
        ),
    ]
