# Generated by Django 3.1.5 on 2022-02-27 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20220226_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_form', models.CharField(max_length=35)),
                ('reading_form', models.CharField(max_length=35)),
                ('dict_form', models.CharField(max_length=35)),
                ('part_of_speech_array', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.TextField()),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='books.word')),
            ],
        ),
    ]
