# Generated by Django 3.1.5 on 2022-02-27 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_definition_word'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='story',
            new_name='story_type',
        ),
    ]
