# Generated by Django 3.1.5 on 2022-03-10 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20220227_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indices', models.CharField(max_length=1000)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_words', to='books.book')),
                ('words', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_words', to='books.word')),
            ],
        ),
        migrations.CreateModel(
            name='BookLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indices', models.CharField(max_length=100)),
                ('line_romaji', models.CharField(max_length=200)),
                ('line_japanese', models.CharField(max_length=200)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_lines', to='books.book')),
                ('words', models.ManyToManyField(related_name='book_lines', to='books.Word')),
            ],
        ),
    ]
