# Generated by Django 3.1.5 on 2022-03-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20220228_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='is_all_kana',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bookline',
            name='indices',
            field=models.CharField(default='', max_length=100),
        ),
    ]
