# Generated by Django 3.1.5 on 2022-03-03 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hontone', '0002_userword_worddeck'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worddeck',
            old_name='books',
            new_name='book',
        ),
    ]
